/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulator;

/**
 *
 * @author khada
 */
public class KALKULATOR extends javax.swing.JFrame {
    String angka;
    double jumlah, bil1, bil2;
    int pilih;
    /**
     * Creates new form KALKULATOR
     */
    public KALKULATOR() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TAMPIL = new javax.swing.JTextField();
        HAPUS = new javax.swing.JButton();
        ANGKA7 = new javax.swing.JButton();
        ANGKA4 = new javax.swing.JButton();
        ANGKA1 = new javax.swing.JButton();
        ANGKA2 = new javax.swing.JButton();
        ANGKA8 = new javax.swing.JButton();
        ANGKA0 = new javax.swing.JButton();
        ANGKA5 = new javax.swing.JButton();
        ANGKA3 = new javax.swing.JButton();
        ANGKA6 = new javax.swing.JButton();
        ANGKA9 = new javax.swing.JButton();
        BTNTITIK = new javax.swing.JButton();
        BTNBAGI = new javax.swing.JButton();
        BTNKALI = new javax.swing.JButton();
        BTNKURANG = new javax.swing.JButton();
        BTNTAMBAH = new javax.swing.JButton();
        BTNHASIL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TAMPIL.setEditable(false);
        TAMPIL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TAMPIL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        HAPUS.setText("C");
        HAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HAPUSActionPerformed(evt);
            }
        });

        ANGKA7.setText("7");
        ANGKA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA7ActionPerformed(evt);
            }
        });

        ANGKA4.setText("4");
        ANGKA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA4ActionPerformed(evt);
            }
        });

        ANGKA1.setText("1");
        ANGKA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA1ActionPerformed(evt);
            }
        });

        ANGKA2.setText("2");
        ANGKA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA2ActionPerformed(evt);
            }
        });

        ANGKA8.setText("8");
        ANGKA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA8ActionPerformed(evt);
            }
        });

        ANGKA0.setText("0");
        ANGKA0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA0ActionPerformed(evt);
            }
        });

        ANGKA5.setText("5");
        ANGKA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA5ActionPerformed(evt);
            }
        });

        ANGKA3.setText("3");
        ANGKA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA3ActionPerformed(evt);
            }
        });

        ANGKA6.setText("6");
        ANGKA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA6ActionPerformed(evt);
            }
        });

        ANGKA9.setText("9");
        ANGKA9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANGKA9ActionPerformed(evt);
            }
        });

        BTNTITIK.setText(".");
        BTNTITIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTITIKActionPerformed(evt);
            }
        });

        BTNBAGI.setText("/");
        BTNBAGI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBAGIActionPerformed(evt);
            }
        });

        BTNKALI.setText("X");

        BTNKURANG.setText("-");
        BTNKURANG.setToolTipText("");
        BTNKURANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKURANGActionPerformed(evt);
            }
        });

        BTNTAMBAH.setText("+");
        BTNTAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTAMBAHActionPerformed(evt);
            }
        });

        BTNHASIL.setText("=");
        BTNHASIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHASILActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAMPIL)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ANGKA7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ANGKA8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ANGKA9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNKALI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNBAGI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ANGKA4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ANGKA5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ANGKA6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNKURANG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ANGKA1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ANGKA2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ANGKA3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ANGKA0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BTNTITIK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BTNHASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BTNTAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TAMPIL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HAPUS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBAGI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANGKA7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNKALI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANGKA4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNKURANG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANGKA1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNTAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHASIL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNTITIK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANGKA0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ANGKA9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA9ActionPerformed
        angka += "9";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA9ActionPerformed

    private void ANGKA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA6ActionPerformed
        angka += "6";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA6ActionPerformed

    private void ANGKA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA3ActionPerformed
        angka += "3";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA3ActionPerformed

    private void ANGKA0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA0ActionPerformed
    angka += "0";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA0ActionPerformed

    private void ANGKA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA1ActionPerformed
        angka += "1";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA1ActionPerformed

    private void ANGKA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA2ActionPerformed
        angka += "2";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA2ActionPerformed

    private void ANGKA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA4ActionPerformed
        angka += "4";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA4ActionPerformed

    private void ANGKA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA5ActionPerformed
        angka += "5";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA5ActionPerformed

    private void ANGKA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA7ActionPerformed
        angka += "7";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA7ActionPerformed

    private void ANGKA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANGKA8ActionPerformed
        angka += "8";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_ANGKA8ActionPerformed

    private void BTNTITIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTITIKActionPerformed
        angka += ",";
    TAMPIL.setText(angka);
    }//GEN-LAST:event_BTNTITIKActionPerformed

    private void HAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HAPUSActionPerformed
    TAMPIL.setText(angka);
    bil1 = 0.0;
    bil2 = 0.0;
    jumlah = 0.0;
    angka = "";
    }//GEN-LAST:event_HAPUSActionPerformed

    private void BTNTAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTAMBAHActionPerformed
        bil1 = Double.parseDouble(angka);
        TAMPIL.setText("+");
        angka = "";
        pilih=1;
    }//GEN-LAST:event_BTNTAMBAHActionPerformed

    private void BTNKURANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKURANGActionPerformed
        bil1 = Double.parseDouble(angka);
        TAMPIL.setText("-");
        angka = "";
        pilih=2;
    }//GEN-LAST:event_BTNKURANGActionPerformed

    private void BTNBAGIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBAGIActionPerformed
        bil1 = Double.parseDouble(angka);
        TAMPIL.setText("/");
        angka = "";
        pilih=4;
    }//GEN-LAST:event_BTNBAGIActionPerformed

    private void BTNHASILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHASILActionPerformed
        switch (pilih){
                case 1:
                    bil2 = Double.parseDouble(angka);
                    jumlah = bil1+bil2;
                    angka = Double.toString(jumlah);
                    TAMPIL.setText(angka);
                    break;
                case 2:
                    bil2 = Double.parseDouble(angka);
                    jumlah = bil1-bil2;
                    angka = Double.toString(jumlah);
                    TAMPIL.setText(angka);
                    break;
                case 3:
                    bil2 = Double.parseDouble(angka);
                    jumlah = bil1*bil2;
                    angka = Double.toString(jumlah);
                    TAMPIL.setText(angka);
                    break;
                case 4:
                    bil2 = Double.parseDouble(angka);
                    jumlah = bil1/bil2;
                    angka = Double.toString(jumlah);
                    TAMPIL.setText(angka);
                    break;
                default:
                    break;
    }//GEN-LAST:event_BTNHASILActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KALKULATOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KALKULATOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANGKA0;
    private javax.swing.JButton ANGKA1;
    private javax.swing.JButton ANGKA2;
    private javax.swing.JButton ANGKA3;
    private javax.swing.JButton ANGKA4;
    private javax.swing.JButton ANGKA5;
    private javax.swing.JButton ANGKA6;
    private javax.swing.JButton ANGKA7;
    private javax.swing.JButton ANGKA8;
    private javax.swing.JButton ANGKA9;
    private javax.swing.JButton BTNBAGI;
    private javax.swing.JButton BTNHASIL;
    private javax.swing.JButton BTNKALI;
    private javax.swing.JButton BTNKURANG;
    private javax.swing.JButton BTNTAMBAH;
    private javax.swing.JButton BTNTITIK;
    private javax.swing.JButton HAPUS;
    private javax.swing.JTextField TAMPIL;
    // End of variables declaration//GEN-END:variables
}
